#include "errno.h"

char* deployERRvariable(int error){
    char* string;
    if(error == EPERM)string = (char*)"Operation not permitted";
    if(error == ENOENT)string = (char*)"No such file or directory";
    if(error == ESRCH)string = (char*)"No such process";
    if(error == EINTR)string = (char*)"Interrupted system call";
    if(error == EIO)string = (char*)"I/O error";
    if(error == ENXIO)string = (char*)"No such device or address";
    if(error == E2BIG )string = (char*)"Argument list too long";
    if(error == ENOEXEC)string = (char*)"Exec format error";
    if(error == EBADF)string	= (char*)"Bad file number";
    if(error == ECHILD)string = (char*)"No child processes";
    if(error == EAGAIN)string = (char*)"Try again";
    if(error == ENOMEM)string = (char*)"out of memory";
    if(error == EACCES)string = (char*)"Permission denied";
    if(error == EFAULT)string = (char*)"Bad address";
    if(error == ENOTBLK)string = (char*)"Block device required";
    if(error == EBUSY)string = (char*)"Device or resource busy";
    if(error == EEXIST)string = (char*)"File exists";
    if(error == EXDEV)string = (char*)"Cross-device link";
    if(error == ENODEV)string = (char*)"No such device";
    if(error == ENOTDIR)string = (char*)"Not a directory";
    if(error == EISDIR)string = (char*)"Is a directory";
    if(error == EINVAL)string = (char*)"Invalid argument";
    if(error == ENFILE)string = (char*)"File table overflow";
    if(error == EMFILE)string = (char*)"Too many open files";
    if(error == ENOTTY)string = (char*)"Not a typewriter";
    if(error == ETXTBSY)string = (char*)"Text file busy";
    if(error == EFBIG)string = (char*)"File too large";
    if(error == ENOSPC)string = (char*)"No space left on device";
    if(error == ESPIPE)string = (char*)"Illegal seek";
    if(error == EROFS)string = (char*)"Read-only file system";
    if(error == EMLINK)string = (char*)"Too many links";
    if(error == EPIPE)string = (char*)"Broken pipe";
    if(error == EDOM)string = (char*)"Math argument out of domain of func";
    if(error == ERANGE)string = (char*)"Math result not representable";
    if(error == EDEADLK)string = (char*)"Resource deadlock would occur";
    if(error == ENAMETOOLONG)string = (char*)"File name too long";
    if(error == ENOLCK)string = (char*)"No record locks available";
    if(error == ENOSYS)string = (char*)"Function not implemented";
    if(error == ENOTEMPTY)string = (char*)"Directory not empty";
    if(error == ELOOP)string = (char*)"Too many symbolic links encountered";

    if(error == ENOMSG)string = (char*)"No message of desired type";
    if(error == EIDRM)string = (char*)"Identifier removed";
    if(error == ECHRNG)string = (char*)"Channel number out of range";
    if(error == EL2NSYNC)string = (char*)"Level 2 not synchronized";
    if(error == EL3HLT)string = (char*)"Level 3 halted";
    if(error == EL3RST)string = (char*)"Level 3 reset";
    if(error == ELNRNG)string = (char*)"Link number out of range";
    if(error == EUNATCH)string = (char*)"Protocol driver not attached";
    if(error == ENOCSI)string = (char*)"No CSI structure available";
    if(error == EL2HLT)string = (char*)"Level 2 halted";
    if(error == EBADE)string = (char*)"Invalid exchange";
    if(error == EBADR)string = (char*)"Invalid request descriptor";
    if(error == EXFULL)string = (char*)"Exchange full";
    if(error == ENOANO)string = (char*)"No anode";
    if(error == EBADRQC)string = (char*)"Invalid request code";
    if(error == EBADSLT)string = (char*)"Invalid slot";
    if(error == EBFONT)string = (char*)"Bad font file format";
    if(error == ENOSTR)string = (char*)"Device not a stream";
    if(error == ENODATA)string = (char*)"No data available";
    if(error == ETIME)string = (char*)"Timer expired";
    if(error == ENOSR)string = (char*)"Out of streams resources";
    if(error == ENONET)string = (char*)"Machine is not on the network";
    if(error == ENOPKG)"Package not installed";
    if(error == EREMOTE)string = (char*)"Object is remote";
    if(error == ENOLINK)string = (char*)"Link has been severed";
    if(error == EADV)string = (char*)"Advertise error";
    if(error == ESRMNT)string = (char*)"Srmount error";
    if(error == ECOMM)string = (char*)"Communication error on send";
    if(error == EPROTO)string = (char*)"Protocol error";
    if(error == EL2NSYNC)string = (char*)"Level 2 not synchronized#define EMULTIHOP	72	0x48	0x..ffb8	Multihop attempted";
    if(error == EDOTDOT)string = (char*)"RFS specific error";
    if(error == EBADMSG)string = (char*)"Not a data message";
    if(error == EOVERFLOW)string = (char*)"Value too large for defined data type";
    if(error == ENOTUNIQ)string = (char*)"Name not unique on network";
    if(error == EBADFD)string = (char*)"File descriptor in bad state";
    if(error == EREMCHG)string = (char*)"Remote address changed";
    if(error == ELIBACC)string = (char*)"Can not access a needed shared library";
    if(error == ELIBBAD)string = (char*)"Accessing a corrupted shared library";
    if(error == ELIBSCN)string = (char*)".lib section in a.out corrupted";
    if(error == ELIBMAX)string = (char*)"Attempting to link in too many shared libraries";
    if(error == ELIBEXEC)string = (char*)"Cannot exec a shared library directly";
    if(error == EILSEQ)string = (char*)"Illegal byte sequence";
    if(error == ERESTART)string = (char*)"Interrupted system call should be restarted";
    if(error == ESTRPIPE)string = (char*)"Streams pipe error";
    if(error == EUSERS)string = (char*)"Too many users";
    if(error == ENOTSOCK)string = (char*)"Socket operation on non-socket";
    if(error == EDESTADDRREQ)string = (char*)"Destination address required";
    if(error == EMSGSIZE)string = (char*)"Message too long";
    if(error == EPROTOTYPE)string = (char*)"Protocol wrong type for socket";
    if(error == ENOPROTOOPT)string = (char*)"Protocol not available";
    if(error == EPROTONOSUPPORT)string = (char*)"Protocol not supported";
    if(error == ESOCKTNOSUPPORT)string = (char*)"Socket type not supported";
    if(error == EOPNOTSUPP)string = (char*)"Operation not supported on transport endpoint";
    if(error == EPFNOSUPPORT)string = (char*)"Protocol family not supported";
    if(error == EAFNOSUPPORT)string = (char*)"Address family not supported by protocol";
    if(error == EADDRINUSE)string = (char*)"Address already in use";
    if(error == EADDRNOTAVAIL)string = (char*)"Cannot assign requested address";
    if(error == ENETDOWN)string = (char*)"Network is down";
    if(error == ENETUNREACH)string = (char*)"Network is unreachable";
    if(error == ENETRESET)string = (char*)"Network dropped connection because of reset";
    if(error == ECONNABORTED)string = (char*)"Software caused connection abort";
    if(error == ECONNRESET)string = (char*)"Connection reset by peer";
    if(error == ENOBUFS)string = (char*)"No buffer space available";
    if(error == EISCONN)string = (char*)"Transport endpoint is already connected";
    if(error == ENOTCONN)string = (char*)"Transport endpoint is not connected";
    if(error == ESHUTDOWN)string = (char*)"Cannot send after transport endpoint shutdown";
    if(error == ETOOMANYREFS)string = (char*)"Too many references: cannot splice";
    if(error == ETIMEDOUT)string = (char*)"Connection timed out";
    if(error == ECONNREFUSED)string = (char*)"Connection refused";
    if(error == EHOSTDOWN)string = (char*)"Host is down";
    if(error == EHOSTUNREACH)string = (char*)"No route to host";
    if(error == EALREADY)string = (char*)"Operation already in progress";
    if(error == EINPROGRESS)string = (char*)"Operation now in progress";
    if(error == ESTALE)string = (char*)"Stale NFS file handle";
    if(error == EUCLEAN)string = (char*)"Structure needs cleaning";
    if(error == ENOTNAM)string = (char*)"Not a XENIX named type file";
    if(error == ENAVAIL)string = (char*)"No XENIX semaphores available";
    if(error == EISNAM)string = (char*)"Is a named type file";
    if(error == EREMOTEIO)string = (char*)"Remote I/O error";
    if(error == EDQUOT)string = (char*)"Quota exceeded";
    if(error == ENOMEDIUM)string = (char*)"No medium found";
    if(error == EMEDIUMTYPE)string = (char*)"Wrong medium type";
    if(error == ECANCELED)string = (char*)"Operation Canceled";
    if(error == ENOKEY)string = (char*)"Required key not available";
    if(error == EKEYEXPIRED)string = (char*)"Key has expired";
    if(error == EKEYREVOKED)string = (char*)"Key has been revoked";
    if(error == EKEYREJECTED)string = (char*)"Key was rejected by service";
    if(error == EOWNERDEAD)string = (char*)"Owner died";
    if(error == ENOTRECOVERABLE)string = (char*)"State not recoverable";
    if(error == ERFKILL)string = (char*)"Operation not possible due to RF-kill";
    if(error == EHWPOISON)string = (char*)"Memory page has hardware error";
    if(error == ERESTARTSYS)string = (char*)"0x..ff200";
    if(error == ERESTARTNOINTR)string = (char*)"0x..ff1ff";
    if(error == ERESTARTNOHAND)string = (char*)"restart if no handler";
    if(error == ENOIOCTLCMD)string = (char*)"No ioctl command";
    if(error == ERESTART_RESTARTBLOCK)string = (char*)"restart by calling sys_restart_syscall";
    if(error == EBADHANDLE)string = (char*)"Illegal NFS file handle";
    if(error == ENOTSYNC)string = (char*)"Update synchronization mismatch";
    if(error == EBADCOOKIE)string = (char*)"Cookie is stale";
    if(error == ENOTSUPP)string = (char*)"Operation is not supported";
    if(error == ETOOSMALL)string = (char*)"Buffer or request is too small";
    if(error == ESERVERFAULT)string = (char*)"An untranslatable error occurred";
    if(error == EBADTYPE)string = (char*)"Type not supported by server";
    if(error == EJUKEBOX)string = (char*)"Request initiated, but will not complete before timeout";
    if(error == EIOCBQUEUED)string = (char*)"iocb queued, will get completion event";
    if(error == EIOCBRETRY)string = (char*)"iocb queued, will trigger a retry";
    return string;
}
